👍(bin) `update-local-packages`コマンドが全てのPKGBUILDを対象に実行されるよう変更

diff --git a/bin/executable_update-local-packages b/bin/executable_update-local-packages
--- a/bin/executable_update-local-packages
+++ b/bin/executable_update-local-packages
@@ -2,6 +2,13 @@
 
 set -eu
 
-cd ~/abs/neovim-git
+# PKGBUILDが存在するディレクトリを検索
+find ~/abs -type f -name PKGBUILD -exec dirname {} \; | while IFS= read -r dir; do
+        cd "$dir" || continue;
 
-makepkg -si && chezmoi add PKGBUILD
+        if makepkg -si; then
+                chezmoi add PKGBUILD
+        else
+                echo "makepkg -si failed in directory ${dir}."
+        fi
+done
